### ISSUE TITLE
[Bug]: The welcome banner is not closing.

### ISSUE THREAD

**Issue by ironrustem** [Jigsaw-Code/outline-apps#2286] opened 2024-11-21 19:26 UTC
### Application

Outline Client

### Describe the bug

![photo_2024-11-21 22 22 28](https://github.com/user-attachments/assets/33489467-5b17-47f2-aa74-e91c489a789b)

The welcome banner is not closing.
iOS: 15

### Steps to reproduce

1. Download the app
2. Launch for the first time

### Outline Version

1.14.0

### What operation system are you using?

iOS

### Operating System Version

Ios 15.0

**Comment by m99vpy** [comment] 2024-11-21 20:59
Same for me: MacOS BigSur 11.7, Outline client 1.14.0

**Comment by ssemeniuta** [comment] 2024-11-23 09:23
+1

**Comment by Saint4script** [comment] 2024-11-24 14:28
+1 on macOS BigSur 11.7.10 MacBook pro 2020

**Comment by screwgoth** [comment] 2024-11-24 18:35
+1 on macOS BigSur 11.7.10 Macbook Air 2020

**Comment by gromer** [comment] 2024-11-25 21:24
+1 on macOS 11.7.10 (late 2013 MBP 😂)

**Comment by sbruens** [comment] 2024-11-26 20:44
Dupe of iOS #2276 and macOS #2283.

**Closed by sbruens** 2024-11-26 20:44 UTC
Labels: bug

**Comment by vpn-octopus** [comment] 2024-11-28 00:31
+1 на macOS BigSur 11.7.10 Macbook PRO   2014 

Есть варианты решения?

**Comment by talyguryn** [comment] 2024-12-05 11:36
same issue on mbp 13 2014 big sur 11.7.10 

found two temporary solutions:
- try [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) with your `ss://...` key
- (if you run the server) install [setup-ipsec-vpn](https://github.com/hwdsl2/setup-ipsec-vpn) and set up native vpn in macos settings
