### ISSUE TITLE
Reset data usage + time limitation

### ISSUE THREAD

**Issue by imatthew-nq** [Jigsaw-Code/outline-apps#2021] opened 2024-05-23 15:47 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Application

Outline Manager

### What are you trying to do? What is your use case?

Hello
Is it possible to create a button to reset the data usage of each key in the outline-manager?
And the other cool feature that would be useful to be added, is limitation by date (from yyyy-mm-dd to yyyy-mm-dd).

If any above features already exist, could you please guide me on how can I do it? (Even if it is possible via API ShadowSocks Container)

### Describe the solution you'd like.

Just like other VPN panels that have this feature for example x-ui panel.

**Comment by sbruens** [comment] 2024-06-03 15:34
Duplicate of #1866

**Comment by sbruens** [comment] 2024-06-03 15:34
Also #1884

**Closed by sbruens** 2024-06-03 15:34 UTC
Labels: feature request
