### ISSUE TITLE
 Data limit doesn't work when set to 0 bytes

### ISSUE THREAD

**Issue by 1000MilesAway** [Jigsaw-Code/outline-apps#1780] opened 2023-11-09 19:29 UTC
Hello there!
Im noticed that couple days ago many keys with data limit = 0 bytes - working just fine, as there is no limits at all!

Restarting server and turn on\off limits - helps only with some keys, and with couple repeats.

What could be source of that problem, and how fix it?

**Comment by maddyhof** [comment] 2023-11-13 16:16
Thanks for reaching out. It could be that Outline is reading a data limit of 0 as "no limit" rather than "no data." It may be that if you set a data limit of 1 byte it'll work. We'll test this and look into clarifying the intended behavior.

**Comment by sbruens** [comment] 2024-07-03 20:27
Dupe of #1515

**Closed by sbruens** 2024-07-03 20:27 UTC
Labels: bug, needs test, usage/data controls
