### ISSUE TITLE
Change DNS servers

### ISSUE THREAD

**Issue by Rim4ik-s** [Jigsaw-Code/outline-apps#2200] opened 2024-09-07 06:06 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Application

Outline Manager

### What are you trying to do? What is your use case?

Hello everyone! I recently started using Outline Client, and so far I like everything except for one issue—I can't change the DNS servers. I've tried various methods for Ubuntu: used iptables, modified settings in resolv.conf, and installed different DNS proxies. But as far as I understand, the DNS servers are hard-coded into the program. Does anyone know how to change the DNS servers without having to rebuild the project or edit the code? I just don't have time for that.

Apologies if this message is off-topic, and I'm happy to answer any additional questions!

### Describe the solution you'd like.

Perhaps it would be worth incorporating DNS server configuration into one of the config files outside of the Docker containers.

**Comment by sbruens** [comment] 2024-09-10 20:07
Thanks for reporting. This seems like a dupe of #568.

**Closed by sbruens** 2024-09-10 20:07 UTC
Labels: feature request
