### ISSUE TITLE
macos sonoma menu bar

### ISSUE THREAD

**Issue by cherr7** [Jigsaw-Code/outline-apps#1727] opened 2023-09-27 13:28 UTC
This issue tracker is for bug reports only. **If you want to request troubleshooting assistance with Outline Manager or Outline Client, please do not submit a bug here. Instead, please contact us using our [support website](https://support.getoutline.org/s/contactsupport).** Developers using Outline SDK, please post your questions on the [SDK Discussion board](https://github.com/Jigsaw-Code/outline-sdk/discussions).

**Describe the bug**
nothing can be clicked in the menu bar icon on macos sonoma

**To reproduce**
download macos sonoma
click the outline logo in the taskbar

**Expected behavior**
to be able to use the app

**Screenshots**

**Client system (please complete the following information):**
 - Outline Client Version: latest app store version
 -  - Your Operating System: latest macos

**Submit feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

**Comment by Igralino** [comment] 2023-09-27 14:35
+1 

It is not possible to use Outline client on macOS Sonoma

**Comment by abugray** [comment] 2023-09-27 17:37
+1

**Comment by DenisK-Voodoo** [comment] 2023-09-27 17:38
+1, CRITICAL for macOS

**Comment by vyacheslavslava** [comment] 2023-09-28 00:03
+1

**Comment by r1chbrown** [comment] 2023-09-28 00:04
+1

**Comment by vyacheslavslava** [comment] 2023-09-28 00:10
The application works fine if you hold down the Command key when clicking the mouse.

**Comment by cherr7** [comment] 2023-09-28 00:11
> The application works fine if you hold down the Command key when clicking the mouse.

works for me as well

**Comment by vyacheslavslava** [comment] 2023-09-28 00:23
in addition to pressing the command key when clicking the mouse, it helps to shift focus to any open program on macOS before opening the application; in this case, Outline works correctly.
In any case, I agree that this is a critical bug for macOS.

**Comment by D4D25A** [comment] 2023-09-28 01:17
It's unusual how the Outline client is still yet to be ported to a Universal MacOS binary.

**Comment by AGluk** [comment] 2023-10-07 06:49
+1
Adopting the program to Apple Silicon support, as mentioned before, would be great!
And fixing the bug in Sonoma :)
Thank you!

**Comment by fortuna** [comment] 2023-10-09 15:11
We've been struggling with macOS because cordova-osx has been deprecated and it has not been updated in a while.

We have a new version or the macOS client based on Mac Catalyst that allows us to use cordova-ios, which is still supported and updated. I'm hopeful that will address those issues. @daniellacosse @sbruens can we release the Mac Catalyst version in the next release?

I'll note that we don't have a Sonoma machine, so I'm not 100% sure if it will actually fix the problem, but the new code seems to work much better on Ventura.

**Comment by flyq** [comment] 2023-10-19 01:05
I meet this bug too, and sometime I just tap esc, and it works fine

**Comment by jlrodriguezdev** [comment] 2023-10-20 00:09
Still not working, so i am connecting from Mac os Settings/Network VPN

**Comment by romanmorozov81** [comment] 2023-10-27 11:05
the same bug too

**Comment by dijtex** [comment] 2023-10-29 17:23
Same bug.

**Comment by wangw469** [comment] 2023-11-10 07:54
> > We've been struggling with macOS because cordova-osx has been deprecated and it has not been updated in a while.
> > We have a new version or the macOS client based on Mac Catalyst that allows us to use cordova-ios, which is still supported and updated. I'm hopeful that will address those issues. @daniellacosse @sbruens can we release the Mac Catalyst version in the next release?
> > I'll note that we don't have a Sonoma machine, so I'm not 100% sure if it will actually fix the problem, but the new code seems to work much better on Ventura.
> 
> We're planning to release the Catalyst version of the Mac client soon! @sbruens and I are sitting down this week to walk through the final steps.

Do you mean this PR: https://github.com/Jigsaw-Code/outline-client/pull/1630
Maybe others interested about it can make our contribution.

**Comment by fortuna** [comment] 2023-11-10 16:52
We desperately need an Apple specialist who can make our Mac Catalyst app build successfully in debug mode. Our old macOS client, based on the deprecated cordova-osx is not working. 

The issue we are seeing is conflicts between bundles with common dependencies. @sbruens can add more detail.

**Comment by wangw469** [comment] 2023-11-12 02:07
> It's the archive process that's failing, and we're under the impression that there are alternative ways to release the MacOS app that don't require an Apple-style archival, skipping the duplicate dependency check - if anyone knows what those alternative release methods are, that would be super helpful.

Can you please give me a issue link? I'm not a iOS expert but I will try to see if I can make any contribution.

Thanks.

**Comment by sbruens** [comment] 2023-11-13 15:04
> Do you mean this PR: #1630 Maybe others interested about it can make our contribution.

That's the one. We've been having issues with archiving the Mac Catalyst version and I am pretty new to Apple development so it's been a slow process of trial and error. I just created #1784 to track the particular issue. If anyone has thoughts on how to resolve it that we haven't been thought of yet, we would appreciate the help. I will continue to work on it as well. @wangw469 thank you for offering to take a look as well!

**Comment by arkhipus** [comment] 2023-12-04 21:39
It is still broken on M3 MacBook with Sonoma. The workaround is to hold the Option button while clicking on the app icon

**Comment by zry656565** [comment] 2023-12-08 02:05
Please release the fixed version. tks!

**Comment by sergeich5** [comment] 2023-12-09 11:15
Still broken

**Comment by tonghae** [comment] 2023-12-11 02:06
Found same issue while setting up my new Mac on Sonoma
Workaround with holding cmd key and switching app focus works but still waiting for proper fix

**Comment by Alex-aka-ion** [comment] 2024-01-02 13:00
Still broken :( M2 & Sonoma 14.2.1 (worked well with Sonoma 14.1, but after update won't work). Hold cdm key helps.

**Comment by Darwinium** [comment] 2024-01-04 21:06
Same, M2, Sonoma 14.0. As listed before CMD helps sometimes 😓

**Comment by Alex-aka-ion** [comment] 2024-01-15 19:23
It's interesting that it start working correctly after couple of starts with "cmd" and couple of reboots

**Comment by MaximAfanasenko** [comment] 2024-01-18 07:05
+1

**Comment by sergeich5** [comment] 2024-01-21 15:59
> It's interesting that it start working correctly after couple of starts with "cmd" and couple of reboots

cmd + tab helps

**Comment by wl4g** [comment] 2024-02-01 01:26
> 在 Sonoma 上设置我的新 Mac 时发现同样的问题 按住 cmd 键并切换应用程序焦点的解决方法有效，但仍在等待正确的修复

Thank you very much, it solved my pain

**Comment by jlrodriguezdev** [comment] 2024-02-01 01:28
I encountered the same problem while setting up my new Mac on Sonoma. The workaround of holding down the cmd key and changing the app focus worked, but I'm still waiting for the right solution.

**Comment by wl4g** [comment] 2024-02-01 01:28
> It's interesting that it start working correctly after couple of starts with "cmd" and couple of reboots

Damn, I even wonder if it was designed this way intentionally?

**Comment by Darwinium** [comment] 2024-02-01 10:57
CMD (and sometimes I need to add Shift) works fine, but of course, it's not the best way.

**Comment by user334** [comment] 2024-02-07 21:22
Hey @daniellacosse and @sbruens! 

Perhaps it's time to lock this issue from new comments to avoid "useless plusones" and pin it in the issues section so that the increasing number of people who update their machines to Sonoma and now find Outline "not usable" can easily find that this is already "known" and also the proposed "solution" here?

As for myself I switched to [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) client while waiting the fix here.

**Comment by sbruens** [comment] 2024-02-29 19:59
This issue is fixed in the latest release v1.12.1, which will gradually rollout over the next 7 days. Please let us know if you continue to have issues on the new version.

**Closed by sbruens** 2024-02-29 19:59 UTC
Labels: bug, os/macos
