### ISSUE TITLE
[Bug]: Can connect to server but cannot connect to the Internet on Outline VPN

### ISSUE THREAD

**Issue by ajayjjain** [Jigsaw-Code/outline-apps#1974] opened 2024-04-15 18:37 UTC
### Application

Outline Client

### Describe the bug

I'm able to connect to the Outline server successfully. However, once I am on the VPN, I am not able to access the Internet. I am able to access the Internet when I am not connected to the Outline server, but connecting to the Outline server prevents me from getting onto the Internet.

### Steps to reproduce

1. Open Outline Client
2. Connect to an Outline server
3. Attempt to go on the Internet

### What did you expect to happen?

I expect to be able to use the Internet normally as I do when I am not connected to the VPN

### What actually happened?

I cannot connect to the Internet, I cannot load web pages, respond to Slack messages, etc.

### Outline Version

1.12.1

### What operation system are you using?

macOS

### Operating System Version

Ventura 13.5.2

**Comment by ajayjjain** [comment] 2024-04-22 21:21
@daniellacosse I submitted feedback weeks ago, at least twice. I've made two Reddit posts, and no one from Outline customer support has reached out to me.

**Comment by ajayjjain** [comment] 2024-04-22 21:29
@daniellacosse thank you!

**Comment by yehtetmaungmaung** [comment] 2024-05-15 06:30
I'm having the same issue. Outline server is hosted on AWS lightsail with Ubuntu 20.04
Server Version is 1.9.0
While connected to vpn, I can still ssh into lightsail server, but cannot access internet. So I call some websites with curl and the output is could not resolve host. I'm still trying to understand what's happening because 2 weeks ago before I joined this company, it was working and the data transferred in the last 30 days was 1.1TB.

**Comment by sbruens** [comment] 2024-08-19 18:42
Could you provide more details on how you were able to reproduce this issue so we can further assist you. Please include details like hosting provider, operating system, commands run, etc.

For linux clients, can you try our experimental CLI to see if that works: https://github.com/Jigsaw-Code/outline-sdk/tree/main/x/examples/outline-cli.

**Comment by sbruens** [comment] 2024-09-17 19:47
Hi there,

We're closing this issue due to inactivity. We haven't heard back from you in a while, and aim to keep our issue tracker organized.

If you're still experiencing this problem or have any additional information to share, please feel free to reopen this issue or create a new one.

Thank you for your understanding!

**Closed by sbruens** 2024-09-17 19:47 UTC
Labels: needs more info, os/macos, customer support
