### ISSUE TITLE
Whatsapp and Telegram Video/Voice calls are not working.

### ISSUE THREAD

**Issue by mmx2004** [Jigsaw-Code/outline-apps#1556] opened 2023-01-18 08:11 UTC
Using the new Outline client (1.9.0) in Android and iOS with prefix, Everything is Ok but the Whatsapp and Telegram Video/Voice calls are not working. Whatsapp calls stuck in Connecting... status and then drops.
Not tested in Windows/Mac/Linux versions.
Country: IRAN

**Comment by fortuna** [comment] 2023-02-01 01:22
It's hard to tell what the issue it, but I wonder if this will fix the issue: https://github.com/Jigsaw-Code/outline-go-tun2socks/pull/110

**Comment by morteza102030** [comment] 2023-10-26 09:02
Why is the problem not solved?

**Comment by fortuna** [comment] 2023-11-07 00:47
@morteza102030 It's not clear what the problem is. We haven't been able to prioritize the investigation of this. If someone know what the problem is, please let us know.

**Comment by morteza102030** [comment] 2023-11-07 07:36
> @morteza102030 It's not clear what the problem is. We haven't been able to prioritize the investigation of this. If someone know what the problem is, please let us know.

i don't know what is problem but Whatsapp and Telegram Video/Voice calls are not working when using outline . I entered the access code in other clients and Video/Voice calls didn't work again
So it can be concluded that this issue is related to the **server outline**

**Comment by manhte2** [comment] 2023-12-14 02:04
I'm facing with same issue, Whatsapp message works well, but callling doesn't work, when perform a calling, receiver can see incoming call but cannot establish calling after tap Receip, It hang and the call auto disconnect after serveral seconds

**Comment by sbruens** [comment] 2024-08-13 21:16
Duplicate of #1999

**Closed by sbruens** 2024-08-13 21:16 UTC
Labels: bug, needs investigation
