### ISSUE TITLE
[Bug]: can not install client on windows 10 with no error code 

### ISSUE THREAD

**Issue by qwerllzt** [Jigsaw-Code/outline-apps#2088] opened 2024-08-01 13:22 UTC
### Application

Outline Client

### Describe the bug

When trying to install the Outline client, the following error occurs:
![Снимок экрана (2624)](https://github.com/user-attachments/assets/8f55150e-8651-4342-9bb9-47b1c4c0e42e)
I'm not getting any error codes.

If, after such an installation, you log into the client and try to connect to the server, you receive the following message: "Administrator rights are required to run Outline. If you don't have them, restart your computer and try again, or contact your administrator.". But when running with administrator rights, nothing changes. After the "unsuccessful" installation, no new network adapters appeared.

I tried a solution from this topic - https://github.com/Jigsaw-Code/outline-apps/issues/1007.
I manually ran the add_top_device file.bat, after an unsuccessful launch, renamed the adapter that appeared to outline-tap0 and then ran add_tap_device.bat again. 
The installation and configuration was successful. As a result, I got a Tap Windows Adapter V9 named Outline-tap0. But after launching the client, nothing changed and problems appeared that were from the very beginning. 

It's also very strange that I couldn't run add_tap_device.bat via powershell with administrator rights or by simply clicking on the file. I was given an error that the system could not find this file, although that was what I was trying to run. It was possible to run it only through the cmd command line with administrator rights. At the same time, on the laptop on which the client is also installed, the add_tap_device file.bat runs smoothly if you just click on it. Maybe it has something to do with my problem. 

I also tried to install various old versions of the client, but the same error was everywhere.
I have not been able to solve this problem for a very long time and have tried a lot of different solutions, but nothing has helped. Please help me

### Steps to reproduce

1. Try to install the client 
2. Get the error as in the screenshot

### Outline Version

1.13.1

### What operation system are you using?

Windows

**Comment by sbruens** [comment] 2024-08-27 19:13
Marking as dupe of #1103

**Closed by sbruens** 2024-08-27 19:13 UTC
Labels: bug, os/windows, failure/install
