### ISSUE TITLE
Detour Nationwide IPs to reduce load/costs on the VPN server

### ISSUE THREAD

**Issue by emohandesi** [Jigsaw-Code/outline-apps#2295] opened 2024-11-25 02:07 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Application

Outline Client

### What are you trying to do? What is your use case?

The Outline client should not use the VPN server for IPs that are not blocked within the country it is used. For example, a user accessing an Iranian website within Iran through the Outline client, should not have the connection to go through the VPN server because the website is not blocked within that country.
This will reduce the load on the Outline VPN server and eventually saves costs for the VPN provider in addition to the client that is paying for its VPN.

### Describe the solution you'd like.

The Outline client should bypass requests that go to an IP of the same country as the user and not use the Outline VPN server for them. The reason is that the IP addresses of the same country are not blocked.
The pull request #311 has implemented this bypass approach for local IP addresses. This can be extended to include the IP ranges for each country.
This feature should be turned off by default in order not to change the expected behavior of the app. The following method is the suggested approach to turn on this feature.
1. Static access keys: the keyword `detour=1` can be added to the connection string as shown below:
```
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTozZ2FEYmtzOFloZmg@ol.server.com:29423/?outline=1&detour=1
```
2. Dynamic access keys:
```json
{
    "server": "www.example.com",
    "server_port": 443,
    "method": "chacha20-ietf-poly1305",
    "password": "0MIZb3fhUNDzQBAW11D5Tr",
    "detour": 1,
}
```

**Comment by sbruens** [comment] 2024-11-26 20:48
You are suggesting something we call selective proxying, which is a long-standing feature request #887. Marking as dupe of that to centralize this request.

**Closed by sbruens** 2024-11-26 20:48 UTC
Labels: feature request
